name: Build Android APK Daily

on:
  schedule:
    - cron: '0 18 * * *' # 每天北京时间2点
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Install dependencies
        run: npm install
        working-directory: ./silent-pen

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android APK (debug)
        run: |
          cd silent-pen
          tauri android build

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: silent-pen/src-tauri/gen/android/app/build/outputs/apk/debug/*.apk 