name: Build Android APK Daily

on:
  schedule:
    - cron: '0 18 * * *' # 每天北京时间2点
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './silent-pen/package-lock.json'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./silent-pen/src-tauri -> target"
          key: android-build

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Install dependencies
        run: npm install
        working-directory: ./silent-pen

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: |
          sdkmanager "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Build Android APK (debug)
        run: |
          cd silent-pen
          tauri android build --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-debug
          path: silent-pen/src-tauri/gen/android/app/build/outputs/apk/debug/*.apk
          retention-days: 7
          
      - name: Build Android APK (release)
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd silent-pen
          tauri android build
          
      - name: Upload Release APK
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-release
          path: silent-pen/src-tauri/gen/android/app/build/outputs/apk/release/*.apk
          retention-days: 30 